stages:
- stage: Build 
  jobs:
  - job: build
    pool:
      vmImage: 'Ubuntu-16.04'
    continueOnError: true
    steps:
    - script: echo RADV CDAT Build stage
- stage: Test
  jobs:
    # track deployments on the environment
  - deployment: test 
    pool:
      vmImage: 'Ubuntu-16.04'
    # creates an environment if it doesn’t exist
    environment: 'QAEnvironment'
    strategy:
      # default deployment strategy
      runOnce:
        deploy:
          steps:
          - script: echo Testing my Multi AzureDevOps Multi Pipeline
- stage: deploy
  jobs:
  - job: deploy 
    pool:
      vmImage: 'Ubuntu-16.04'
    continueOnError: true
    steps:
    - script: echo Deploy CDAT application